namespace TestApp.Library1
{
    [default_interface]
    runtimeclass TestStaticLibrary1Class 
    {
        TestStaticLibrary1Class();

        void Test(TestApp.Library4.TestStaticLibrary4Class c);
    }
}
