name: Bug report
description: File a bug report about cppwinrt
title: "Bug:"
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: "Thank you for filing a bug report! 🐛"
  - type: input
    attributes:
      label: Version
      description: What is the version of cppwinrt you're using?
      placeholder: You can find the exact version by running `cppwinrt.exe`.
  - type: textarea
    attributes:
      label: Summary
      description: >
        Please provide a short summary of the bug, along with any information
        you feel relevant to replicating the bug.
  - type: textarea
    attributes:
      label: Reproducible example
      description: >
        Please provide all code needed to reproduce the issue.
      placeholder: |
        #include "winrt/Windows.Foundation.h"

        using namespace winrt;
        using namespace Windows::Foundation;

        int main()
        {
          Uri uri(L"https://kennykerr.ca");
          printf("%ls\n", uri.ToString().c_str());
        }
      render: cpp
  - type: textarea
    attributes:
      label: Expected behavior
      description: "I expected to see this happen:"
  - type: textarea
    attributes:
      label: Actual behavior
      description: "Instead, this happened:"
  - type: textarea
    attributes:
      label: Additional comments
      description: Is there anything else you'd like to share?
    validations:
      required: false
  - type: markdown
    attributes:
      value: "Thank you! ©️➕➕"
