import "TestModuleComponentWidget.idl";

namespace TestModuleComponent
{
    struct WidgetInfo
    {
        TestModuleComponent.Widgets.WidgetSize Size;
        String Description;
    };

    [default_interface]
    runtimeclass TestModuleComponentClass
    {
        TestModuleComponentClass();
        void Test();
        TestModuleComponent.Widgets.Widget CreateWidget();
        WidgetInfo GetWidgetInfo();
        Windows.Foundation.Uri GetUri();
        // Cross-namespace dep: exercises guarded includes in .g.h
        void ApplySettings(Windows.Foundation.Collections.IMapView<String, String> settings);
    }
}
