// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.3.4.5

#ifndef WINRT_test_component_no_pch_Peer2_2_H
#define WINRT_test_component_no_pch_Peer2_2_H
#include "winrt/impl/test_component_no_pch.Peer1.2.h"
#include "winrt/impl/test_component_no_pch.Peer2.1.h"
WINRT_EXPORT namespace winrt::test_component_no_pch::Peer2
{
    struct B
    {
        test_component_no_pch::Peer1::A First;
        int32_t Second;
    };
    inline bool operator==(B const& left, B const& right) noexcept
    {
        return left.First == right.First && left.Second == right.Second;
    }
    inline bool operator!=(B const& left, B const& right) noexcept
    {
        return !(left == right);
    }
}
#endif
