namespace TestModuleComponent2
{
    [default_interface]
    runtimeclass GreeterGroup
    {
        GreeterGroup();
        void Add(TestModuleComponent1.Greeter greeter);
        String GreetAll();
    }
}
