// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.3.4.5

void* winrt_make_test_component_Velocity_Class4()
{
    return winrt::detach_abi(winrt::make<winrt::test_component::Velocity::factory_implementation::Class4>());
}
WINRT_EXPORT namespace winrt::test_component::Velocity
{
    Class4::Class4() :
        Class4(make<test_component::Velocity::implementation::Class4>())
    {
    }
    Class4::Class4(int32_t one, int32_t two) :
        Class4(make<test_component::Velocity::implementation::Class4>(one, two))
    {
    }
    void Class4::Class4_Static2()
    {
        return test_component::Velocity::implementation::Class4::Class4_Static2();
    }
}
