// C++ for the Windows Runtime vv1.0.170303.6
// Copyright (c) 2017 Microsoft Corporation. All rights reserved.

#pragma once


WINRT_EXPORT namespace winrt {

namespace ABI::Windows::ApplicationModel::UserDataTasks::DataProvider {

struct IUserDataTaskDataProviderConnection;
struct IUserDataTaskDataProviderTriggerDetails;
struct IUserDataTaskListCompleteTaskRequest;
struct IUserDataTaskListCompleteTaskRequestEventArgs;
struct IUserDataTaskListCreateOrUpdateTaskRequest;
struct IUserDataTaskListCreateOrUpdateTaskRequestEventArgs;
struct IUserDataTaskListDeleteTaskRequest;
struct IUserDataTaskListDeleteTaskRequestEventArgs;
struct IUserDataTaskListSkipOccurrenceRequest;
struct IUserDataTaskListSkipOccurrenceRequestEventArgs;
struct IUserDataTaskListSyncManagerSyncRequest;
struct IUserDataTaskListSyncManagerSyncRequestEventArgs;
struct UserDataTaskDataProviderConnection;
struct UserDataTaskDataProviderTriggerDetails;
struct UserDataTaskListCompleteTaskRequest;
struct UserDataTaskListCompleteTaskRequestEventArgs;
struct UserDataTaskListCreateOrUpdateTaskRequest;
struct UserDataTaskListCreateOrUpdateTaskRequestEventArgs;
struct UserDataTaskListDeleteTaskRequest;
struct UserDataTaskListDeleteTaskRequestEventArgs;
struct UserDataTaskListSkipOccurrenceRequest;
struct UserDataTaskListSkipOccurrenceRequestEventArgs;
struct UserDataTaskListSyncManagerSyncRequest;
struct UserDataTaskListSyncManagerSyncRequestEventArgs;

}

namespace Windows::ApplicationModel::UserDataTasks::DataProvider {

struct IUserDataTaskDataProviderConnection;
struct IUserDataTaskDataProviderTriggerDetails;
struct IUserDataTaskListCompleteTaskRequest;
struct IUserDataTaskListCompleteTaskRequestEventArgs;
struct IUserDataTaskListCreateOrUpdateTaskRequest;
struct IUserDataTaskListCreateOrUpdateTaskRequestEventArgs;
struct IUserDataTaskListDeleteTaskRequest;
struct IUserDataTaskListDeleteTaskRequestEventArgs;
struct IUserDataTaskListSkipOccurrenceRequest;
struct IUserDataTaskListSkipOccurrenceRequestEventArgs;
struct IUserDataTaskListSyncManagerSyncRequest;
struct IUserDataTaskListSyncManagerSyncRequestEventArgs;
struct UserDataTaskDataProviderConnection;
struct UserDataTaskDataProviderTriggerDetails;
struct UserDataTaskListCompleteTaskRequest;
struct UserDataTaskListCompleteTaskRequestEventArgs;
struct UserDataTaskListCreateOrUpdateTaskRequest;
struct UserDataTaskListCreateOrUpdateTaskRequestEventArgs;
struct UserDataTaskListDeleteTaskRequest;
struct UserDataTaskListDeleteTaskRequestEventArgs;
struct UserDataTaskListSkipOccurrenceRequest;
struct UserDataTaskListSkipOccurrenceRequestEventArgs;
struct UserDataTaskListSyncManagerSyncRequest;
struct UserDataTaskListSyncManagerSyncRequestEventArgs;

}

namespace Windows::ApplicationModel::UserDataTasks::DataProvider {

template <typename T> struct impl_IUserDataTaskDataProviderConnection;
template <typename T> struct impl_IUserDataTaskDataProviderTriggerDetails;
template <typename T> struct impl_IUserDataTaskListCompleteTaskRequest;
template <typename T> struct impl_IUserDataTaskListCompleteTaskRequestEventArgs;
template <typename T> struct impl_IUserDataTaskListCreateOrUpdateTaskRequest;
template <typename T> struct impl_IUserDataTaskListCreateOrUpdateTaskRequestEventArgs;
template <typename T> struct impl_IUserDataTaskListDeleteTaskRequest;
template <typename T> struct impl_IUserDataTaskListDeleteTaskRequestEventArgs;
template <typename T> struct impl_IUserDataTaskListSkipOccurrenceRequest;
template <typename T> struct impl_IUserDataTaskListSkipOccurrenceRequestEventArgs;
template <typename T> struct impl_IUserDataTaskListSyncManagerSyncRequest;
template <typename T> struct impl_IUserDataTaskListSyncManagerSyncRequestEventArgs;

}

}
