// C++ for the Windows Runtime v1.0.161012.5
// Copyright (c) 2016 Microsoft Corporation. All rights reserved.

#pragma once


WINRT_EXPORT namespace winrt {

namespace ABI::Windows::ApplicationModel::Appointments::DataProvider {

struct IAppointmentCalendarCancelMeetingRequest;
struct IAppointmentCalendarCancelMeetingRequestEventArgs;
struct IAppointmentCalendarCreateOrUpdateAppointmentRequest;
struct IAppointmentCalendarCreateOrUpdateAppointmentRequestEventArgs;
struct IAppointmentCalendarForwardMeetingRequest;
struct IAppointmentCalendarForwardMeetingRequestEventArgs;
struct IAppointmentCalendarProposeNewTimeForMeetingRequest;
struct IAppointmentCalendarProposeNewTimeForMeetingRequestEventArgs;
struct IAppointmentCalendarSyncManagerSyncRequest;
struct IAppointmentCalendarSyncManagerSyncRequestEventArgs;
struct IAppointmentCalendarUpdateMeetingResponseRequest;
struct IAppointmentCalendarUpdateMeetingResponseRequestEventArgs;
struct IAppointmentDataProviderConnection;
struct IAppointmentDataProviderTriggerDetails;
struct AppointmentCalendarCancelMeetingRequest;
struct AppointmentCalendarCancelMeetingRequestEventArgs;
struct AppointmentCalendarCreateOrUpdateAppointmentRequest;
struct AppointmentCalendarCreateOrUpdateAppointmentRequestEventArgs;
struct AppointmentCalendarForwardMeetingRequest;
struct AppointmentCalendarForwardMeetingRequestEventArgs;
struct AppointmentCalendarProposeNewTimeForMeetingRequest;
struct AppointmentCalendarProposeNewTimeForMeetingRequestEventArgs;
struct AppointmentCalendarSyncManagerSyncRequest;
struct AppointmentCalendarSyncManagerSyncRequestEventArgs;
struct AppointmentCalendarUpdateMeetingResponseRequest;
struct AppointmentCalendarUpdateMeetingResponseRequestEventArgs;
struct AppointmentDataProviderConnection;
struct AppointmentDataProviderTriggerDetails;

}

namespace Windows::ApplicationModel::Appointments::DataProvider {

struct IAppointmentCalendarCancelMeetingRequest;
struct IAppointmentCalendarCancelMeetingRequestEventArgs;
struct IAppointmentCalendarCreateOrUpdateAppointmentRequest;
struct IAppointmentCalendarCreateOrUpdateAppointmentRequestEventArgs;
struct IAppointmentCalendarForwardMeetingRequest;
struct IAppointmentCalendarForwardMeetingRequestEventArgs;
struct IAppointmentCalendarProposeNewTimeForMeetingRequest;
struct IAppointmentCalendarProposeNewTimeForMeetingRequestEventArgs;
struct IAppointmentCalendarSyncManagerSyncRequest;
struct IAppointmentCalendarSyncManagerSyncRequestEventArgs;
struct IAppointmentCalendarUpdateMeetingResponseRequest;
struct IAppointmentCalendarUpdateMeetingResponseRequestEventArgs;
struct IAppointmentDataProviderConnection;
struct IAppointmentDataProviderTriggerDetails;
struct AppointmentCalendarCancelMeetingRequest;
struct AppointmentCalendarCancelMeetingRequestEventArgs;
struct AppointmentCalendarCreateOrUpdateAppointmentRequest;
struct AppointmentCalendarCreateOrUpdateAppointmentRequestEventArgs;
struct AppointmentCalendarForwardMeetingRequest;
struct AppointmentCalendarForwardMeetingRequestEventArgs;
struct AppointmentCalendarProposeNewTimeForMeetingRequest;
struct AppointmentCalendarProposeNewTimeForMeetingRequestEventArgs;
struct AppointmentCalendarSyncManagerSyncRequest;
struct AppointmentCalendarSyncManagerSyncRequestEventArgs;
struct AppointmentCalendarUpdateMeetingResponseRequest;
struct AppointmentCalendarUpdateMeetingResponseRequestEventArgs;
struct AppointmentDataProviderConnection;
struct AppointmentDataProviderTriggerDetails;

}

}
