name: 'Set up LLVM for MSVC'
description: 'Set up upstream LLVM for targeting MSVC ABI'
inputs:
  llvm-version:
    description: 'LLVM version'
    required: true
    default: '15.0.5'
outputs:
  llvm-path:
    description: "The path in which LLVM is installed to"
    value: ${{ steps.install-llvm.outputs.llvm-path }}
runs:
  using: "composite"
  steps:
    - id: install-llvm
      name: Install LLVM ${{ inputs.llvm-version }}
      shell: pwsh
      run: |
        Invoke-WebRequest "https://github.com/llvm/llvm-project/releases/download/llvmorg-${{ inputs.llvm-version }}/LLVM-${{ inputs.llvm-version }}-win64.exe" -OutFile LLVM-installer.exe
        .\LLVM-installer.exe /S "/D=$pwd\.LLVM" | Out-Null
        rm LLVM-installer.exe
        if (!(Test-Path "$pwd\.LLVM\bin\clang-cl.exe")) { exit 1 }
        Add-Content $env:GITHUB_PATH "$pwd\.LLVM\bin"
        Add-Content $env:GITHUB_OUTPUT "llvm-path=$pwd\.LLVM"

    # Not using the LLVM tools that comes with MSVC.
    - name: Set up LLVM build tools for msbuild
      shell: pwsh
      run: |
        Invoke-WebRequest "https://github.com/zufuliu/llvm-utils/releases/download/v22.09/LLVM_VS2017.zip" -OutFile LLVM_VS2017.zip
        7z x -y "LLVM_VS2017.zip" -o"$pwd\.llvm-utils\"
        cmd /c ".llvm-utils\LLVM_VS2017\install.bat" 1
