namespace TestRuntimeComponent_NamespaceUnderscore
{
    [default_interface]
    runtimeclass TestRuntimeComponentNamespaceUnderscoreClass
    {
        TestRuntimeComponentNamespaceUnderscoreClass();

        void Test();
    }
}
